version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: inventario-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: inventario_db
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario-network
  # Redis para cach√© (futuro)
  # redis:
  #   image: redis:7-alpine
  #   container_name: inventario-redis
  #   restart: unless-stopped
  #   ports:
  #     - '6379:6379'
  #   networks:
  #     - inventario-network

volumes:
  postgres_data:
    driver: local

networks:
  inventario-network:
    driver: bridge
